# Generated by Django 4.2.4 on 2023-09-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookStyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'CookStyleTags',
            },
        ),
        migrations.CreateModel(
            name='FoodTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'FoodTypeTags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price_level', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=3)),
                ('phone_number', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'RestTags',
            },
        ),
        migrations.CreateModel(
            name='TasteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'TasteTags',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_open', models.TimeField()),
                ('mon_close', models.TimeField()),
                ('tue_open', models.TimeField()),
                ('tue_close', models.TimeField()),
                ('wed_open', models.TimeField()),
                ('wed_close', models.TimeField()),
                ('thu_open', models.TimeField()),
                ('thu_close', models.TimeField()),
                ('fri_open', models.TimeField()),
                ('fri_close', models.TimeField()),
                ('sat_open', models.TimeField()),
                ('sat_close', models.TimeField()),
                ('sun_open', models.TimeField()),
                ('sun_close', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'RestOpenHours',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='restaurants.resttag'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories', models.PositiveIntegerField()),
                ('time_of_day_available', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Anytime', 'Anytime')], max_length=20)),
                ('specialty_item', models.BooleanField(default=False)),
                ('cook_style_tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.cookstyletag')),
                ('food_type_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodtypetag')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
                ('taste_tags', models.ManyToManyField(to='restaurants.tastetag')),
            ],
            options={
                'db_table': 'MenuItems',
            },
        ),
    ]
