# Generated by Django 4.2.4 on 2023-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='test',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
