# Generated by Django 4.2.4 on 2023-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Allergy_tag',
            },
        ),
        migrations.CreateModel(
            name='IngredientsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Restriction_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Restriction',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients_tag',
            field=models.ManyToManyField(to='restaurants.ingredientstag'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_allergy_tag',
            field=models.ManyToManyField(to='restaurants.allergy_tag'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_restriction_tag',
            field=models.ManyToManyField(to='restaurants.restriction_tag'),
        ),
    ]
