# Generated by Django 4.2.4 on 2023-09-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='test',
        ),
    ]
