# Generated by Django 4.2.4 on 2023-09-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_allergy_tag_ingredientstag_restriction_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='specialty_item',
            new_name='is_modifiable',
        ),
    ]
