# Generated by Django 4.2.4 on 2023-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_specialty_item_menuitem_is_modifiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='fri_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_close',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_open',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='RestaurantOpenHours',
        ),
    ]
