# Generated by Django 4.2.4 on 2023-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_fri_close_restaurant_fri_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='sun_close',
            field=models.TimeField(null=True),
        ),
    ]
