# Generated by Django 4.2.4 on 2023-09-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_tastetag_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookStyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'CookStyleTags',
            },
        ),
        migrations.CreateModel(
            name='FoodTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'FoodTypeTags',
            },
        ),
        migrations.RenameField(
            model_name='tastetag',
            old_name='taste_tags',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cooking_style',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='itemID',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='taste_tags',
            field=models.ManyToManyField(to='restaurants.tastetag'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resttag',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cook_style_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.cookstyletag'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodtypetag'),
        ),
    ]
