# Generated by Django 4.2.4 on 2023-09-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_cookstyletag_foodtypetag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookstyletag',
            old_name='title',
            new_name='cookStyleTag_title',
        ),
        migrations.RenameField(
            model_name='tastetag',
            old_name='title',
            new_name='tasteTag_title',
        ),
    ]
