# Generated by Django 4.2.4 on 2023-09-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_title_cookstyletag_cookstyletag_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookstyletag',
            old_name='cookStyleTag_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tastetag',
            old_name='tasteTag_title',
            new_name='title',
        ),
    ]
