# Generated by Django 4.2.4 on 2023-09-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_rename_cookstyletag_title_cookstyletag_title_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cookstyletag',
            table='CookSTags',
        ),
    ]
