# Generated by Django 4.2.4 on 2023-11-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_menuitem_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calorie_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
