# Generated by Django 4.2.4 on 2023-09-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_cookstyletag_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cookstyletag',
            table='CookStyleTags',
        ),
    ]
