# Generated by Django 4.2.4 on 2023-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_menuitem_calorie_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='number_of_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
