# Generated by Django 4.2.4 on 2023-09-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_cookstyletag_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookstyletag',
            options={'managed': False},
        ),
    ]
