# Generated by Django 4.2.4 on 2023-09-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_cookstyletag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookstyletag',
            options={},
        ),
    ]
