# Generated by Django 4.2.4 on 2023-12-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_menuitem_number_of_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inverse_sqrt',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='suggestion_vector',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
