# Generated by Django 4.2.4 on 2023-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_remove_menuitem_cook_style_tags_delete_cookstyletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookStyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'CookStyleTags',
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='food_type_tag',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cook_style_tags',
            field=models.ManyToManyField(to='restaurants.cookstyletag'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type_tag',
            field=models.ManyToManyField(to='restaurants.foodtypetag'),
        ),
    ]
