# Generated by Django 4.2.4 on 2023-09-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_cookstyletag_remove_menuitem_food_type_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cook_style_tags',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='food_type_tag',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cook_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.cookstyletag'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.foodtypetag'),
        ),
    ]
