# Generated by Django 4.2.4 on 2023-09-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_remove_menuitem_cook_style_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='cook_style',
            new_name='cook_style_tags',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='food_type',
            new_name='food_type_tag',
        ),
    ]
