# Generated by Django 4.2.4 on 2023-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_rename_cook_style_menuitem_cook_style_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
