# Generated by Django 4.2.4 on 2023-11-25 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_appsatisfactionanalytics_number_of_rating_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsatisfactionanalytics',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
