# Generated by Django 4.2.4 on 2023-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_appsatisfactionanalytics_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergiestaganalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cookstyleanalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ingredienttaganalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='restrictiontaganalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tastetaganalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
    ]
