# Generated by Django 4.2.4 on 2023-12-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_menuitem_number_of_rating'),
        ('analytics', '0005_alter_calorieanalytics_date_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRestaurantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items_added_to_histories', models.PositiveIntegerField()),
                ('date_stamp', models.DateTimeField()),
                ('allergies_tags_most_eliminations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.allergytag')),
                ('cookStyle_tags_most_eliminations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.cookstyletag')),
                ('ingredient_tags_most_eliminations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.ingredienttag')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('restriction_tags_most_eliminations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.restrictiontag')),
                ('taste_tags_most_eliminations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.tastetag')),
                ('top_three_items', models.ManyToManyField(limit_choices_to={'restaurant': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')}, to='restaurants.menuitem')),
            ],
            options={
                'db_table': 'LocalRestaurantAnalytics',
            },
        ),
    ]
