# Generated by Django 4.2.4 on 2023-12-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_menuitem_number_of_rating'),
        ('analytics', '0006_remove_menuitemperformanceanalytics_number_of_added_to_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttagexclusionrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.ingredienttag'),
        ),
        migrations.AlterField(
            model_name='restrictiontagexclusionrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restrictiontag'),
        ),
        migrations.AlterField(
            model_name='tastetagexclusionrecord',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.tastetag'),
        ),
    ]
