# Generated by Django 4.2.4 on 2023-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_ingredienttagexclusionrecord_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallFilterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.IntegerField(choices=[('calories', 'calories'), ('cookstyletag', 'cookstyletag'), ('allergytag', 'allergytag'), ('ingredienttag', 'ingredienttag'), ('restrictiontag', 'restrictiontag'), ('tastetag', 'tastetag')])),
                ('top_3_inclusions', models.JSONField()),
                ('top_3_added', models.JSONField()),
                ('top_3_exclusions', models.JSONField(null=True)),
            ],
        ),
    ]
