# Generated by Django 4.2.4 on 2023-12-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_overallfilteranalytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergytagexclusionrecord',
            name='date_stamp',
        ),
        migrations.RemoveField(
            model_name='ingredienttagexclusionrecord',
            name='date_stamp',
        ),
        migrations.RemoveField(
            model_name='restrictiontagexclusionrecord',
            name='date_stamp',
        ),
        migrations.RemoveField(
            model_name='tastetagexclusionrecord',
            name='date_stamp',
        ),
    ]
