# Generated by Django 4.2.4 on 2023-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_overallfilteranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemperformanceanalytics',
            name='exclusion_count',
            field=models.IntegerField(default=0),
        ),
    ]
