# Generated by Django 4.2.4 on 2023-12-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_allergytagexclusionrecord_date_stamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localrestaurantanalytics',
            name='top_three_items',
        ),
        migrations.AddField(
            model_name='localrestaurantanalytics',
            name='top_three_items',
            field=models.JSONField(null=True),
        ),
    ]
