# Generated by Django 4.2.4 on 2023-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_menuitemperformanceanalytics_exclusion_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallfilteranalytics',
            name='date_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
