# Generated by Django 4.2.4 on 2023-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_remove_localrestaurantanalytics_top_three_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localrestaurantanalytics',
            name='allergies_tags_most_eliminations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='localrestaurantanalytics',
            name='cookStyle_tags_most_eliminations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='localrestaurantanalytics',
            name='ingredient_tags_most_eliminations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='localrestaurantanalytics',
            name='restriction_tags_most_eliminations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='localrestaurantanalytics',
            name='taste_tags_most_eliminations',
            field=models.JSONField(null=True),
        ),
    ]
