# Generated by Django 4.2.4 on 2023-12-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_localrestaurantanalytics_allergies_tags_most_eliminations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localrestaurantanalytics',
            name='cookStyle_tags_most_eliminations',
        ),
    ]
