# Generated by Django 4.2.4 on 2023-12-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_overallfilteranalytics_date_stamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='overallfilteranalytics',
            table='OverallFilterAnalytics',
        ),
    ]
