# Generated by Django 4.2.4 on 2023-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_overallfilteranalytics_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallfilteranalytics',
            name='filter_type',
            field=models.CharField(choices=[('calories', 'calories'), ('cookstyletag', 'cookstyletag'), ('allergytag', 'allergytag'), ('ingredienttag', 'ingredienttag'), ('restrictiontag', 'restrictiontag'), ('tastetag', 'tastetag')], max_length=20),
        ),
    ]
