# Generated by Django 4.2.4 on 2023-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_loginrecord_loginanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginanalytics',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
    ]
