# Generated by Django 4.2.4 on 2023-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_loginanalytics_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsatisfactionanalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='globalanalytics',
            name='date_stamp',
            field=models.DateTimeField(),
        ),
    ]
