# Generated by Django 4.2.4 on 2023-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_ratings_menuitem_history_reviews_menuitem_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='patron_review',
            new_name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
