# Generated by Django 4.2.4 on 2023-10-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_patron_review_reviews_review_reviews_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='menuItem_history',
        ),
    ]
