# Generated by Django 4.2.4 on 2023-11-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_appsatisfaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsatisfaction',
            old_name='patron',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='appsatisfaction',
            name='restaurant',
        ),
    ]
