# Generated by Django 4.2.4 on 2023-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_rename_patron_appsatisfaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsatisfaction',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
