# Generated by Django 4.2.4 on 2023-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_alter_appsatisfaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsatisfaction',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
