# Generated by Django 4.2.4 on 2023-12-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_appsatisfaction_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appsatisfaction',
            table='AppSatisfaction',
        ),
    ]
