# Generated by Django 4.2.4 on 2023-12-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_alter_appsatisfaction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='patron_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
