# Generated by Django 4.2.4 on 2023-12-04 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0011_menuitem_number_of_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSatisfactionTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AppSatisfactionTrends',
            },
        ),
        migrations.CreateModel(
            name='CalorieTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('calorie_level', models.IntegerField(choices=[(0, 'Invalid'), (1, '0 - 199'), (2, '200 - 399'), (3, '400 - 599'), (4, '600 - 799'), (5, '800 - 999'), (6, '1000 - 1199'), (7, '1200 - 1399'), (8, '1400 - 1599'), (9, '1600 - 1799'), (10, '1800 - 1999'), (11, '2000 and up')], default=0, null=True)),
            ],
            options={
                'db_table': 'CalorieTrends',
            },
        ),
        migrations.CreateModel(
            name='TasteTagTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.tastetag')),
            ],
            options={
                'db_table': 'TasteTagTrends',
            },
        ),
        migrations.CreateModel(
            name='RestrictionTagTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restrictiontag')),
            ],
            options={
                'db_table': 'RestrictionTagTrends',
            },
        ),
        migrations.CreateModel(
            name='MenuItemPerformanceTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem')),
            ],
            options={
                'db_table': 'MenuItemPerformanceTrends',
            },
        ),
        migrations.CreateModel(
            name='IngredientTagTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.ingredienttag')),
            ],
            options={
                'db_table': 'IngredientTagTrends',
            },
        ),
        migrations.CreateModel(
            name='CookStyleTagTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.cookstyletag')),
            ],
            options={
                'db_table': 'CookStyleTagTrends',
            },
        ),
        migrations.CreateModel(
            name='AllergyTagTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[], max_length=20, null=True)),
                ('coeff0', models.FloatField()),
                ('coeff1', models.FloatField()),
                ('coeff2', models.FloatField()),
                ('coeff3', models.FloatField()),
                ('coeff4', models.FloatField()),
                ('coeff5', models.FloatField()),
                ('behavior', models.FloatField()),
                ('date_stamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.allergytag')),
            ],
            options={
                'db_table': 'AllergyTagTrends',
            },
        ),
    ]
