# Generated by Django 4.2.4 on 2023-09-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('calorie_limit', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('price_preference', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=5)),
                ('zipcode', models.CharField(max_length=10)),
                ('dietary_restriction', models.CharField(blank=True, max_length=255)),
                ('palate_preference', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Patrons',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem')),
                ('patron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookmarks',
                'unique_together': {('patron', 'menu_item')},
            },
        ),
    ]
