# Generated by Django 4.2.4 on 2023-10-21 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_remove_ratings_meal_history_and_more'),
        ('restaurants', '0009_alter_menuitem_average_rating'),
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuItemHS_datetime', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitem')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MenuItemHistory',
            },
        ),
        migrations.DeleteModel(
            name='MealHistory',
        ),
    ]
