# Generated by Django 4.2.4 on 2023-10-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_menuitem_average_rating'),
        ('patron', '0002_menuitemhistory_delete_mealhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='price_preference',
        ),
        migrations.RemoveField(
            model_name='patronsearchhistory',
            name='dietary_restriction',
        ),
        migrations.AddField(
            model_name='patron',
            name='price_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patronsearchhistory',
            name='allergy_tags',
            field=models.ManyToManyField(to='restaurants.allergytag'),
        ),
        migrations.AddField(
            model_name='patronsearchhistory',
            name='dietary_restriction_tags',
            field=models.ManyToManyField(to='restaurants.restrictiontag'),
        ),
        migrations.AddField(
            model_name='patronsearchhistory',
            name='disliked_ingredients',
            field=models.ManyToManyField(to='restaurants.ingredienttag'),
        ),
        migrations.AddField(
            model_name='patronsearchhistory',
            name='patron_taste_tags',
            field=models.ManyToManyField(to='restaurants.tastetag'),
        ),
    ]
