# Generated by Django 4.2.4 on 2023-09-12 22:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_cookstyletag_foodtypetag_and_more'),
        ('patron', '0002_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='item',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='patron',
            old_name='bod',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patron',
            old_name='patron_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('patron', 'menu_item')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patron',
            name='dietary_restriction',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='patron',
            name='palate_preference',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='Bookmarks',
        ),
        migrations.AlterModelTable(
            name='patron',
            table='Patrons',
        ),
        migrations.CreateModel(
            name='PatronSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('calorie_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('dietary_restriction', models.CharField(blank=True, max_length=255)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('search_datetime', models.DateTimeField(auto_now_add=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PatronSearchHistory',
            },
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealHS_datetime', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitem')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MealHistory',
            },
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmark_id',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='item_name',
        ),
    ]
