# Generated by Django 4.2.4 on 2023-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_allergy_tag_ingredientstag_restriction_tag_and_more'),
        ('patron', '0003_bookmark_bookmarked_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='dietary_restriction',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='palate_preference',
        ),
        migrations.AddField(
            model_name='patron',
            name='Patron_taste_tag',
            field=models.ManyToManyField(to='restaurants.tastetag'),
        ),
        migrations.AddField(
            model_name='patron',
            name='patron_allergy_tag',
            field=models.ManyToManyField(to='restaurants.allergy_tag'),
        ),
        migrations.AddField(
            model_name='patron',
            name='patron_restriction_tag',
            field=models.ManyToManyField(to='restaurants.restriction_tag'),
        ),
    ]
