# Generated by Django 4.2.4 on 2023-09-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0003_rename_item_bookmark_menu_item_rename_bod_patron_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronsearchhistory',
            name='patron',
        ),
        migrations.DeleteModel(
            name='MealHistory',
        ),
        migrations.DeleteModel(
            name='PatronSearchHistory',
        ),
    ]
