# Generated by Django 4.2.4 on 2023-10-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_remove_reviews_menuitem_history'),
        ('patron', '0003_remove_patron_price_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemhistory',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.reviews'),
        ),
    ]
