# Generated by Django 4.2.4 on 2023-11-07 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0005_alter_patron_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronsearchhistory',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patronsearchhistory',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
