# Generated by Django 4.2.4 on 2023-11-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0006_alter_patronsearchhistory_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='calorie_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patronsearchhistory',
            name='calorie_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
