# Generated by Django 4.2.4 on 2023-12-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patron', '0007_patron_calorie_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='profile_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PatronSuggestionVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.PositiveIntegerField()),
                ('tag_table', models.CharField(choices=[('FoodTag', 'FoodTag'), ('TasteTag', 'TasteTag'), ('CookStyle', 'CookStyle'), ('IngredientTag', 'IngredientTag')], max_length=15, null=True)),
                ('rating', models.DecimalField(decimal_places=7, max_digits=8)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_vector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PatronSuggestionVector',
            },
        ),
    ]
