# Generated by Django 4.2.4 on 2023-12-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_patron_profile_updated_patronsuggestionvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronsuggestionvector',
            name='tag_table',
            field=models.CharField(choices=[('FoodTag', 'FoodTag'), ('TasteTag', 'TasteTag'), ('CookTag', 'CookTag'), ('IngredientTag', 'IngredientTag')], max_length=15, null=True),
        ),
    ]
